{% set version = "78.3" %}

package:
  name: icu
  version: "{{ version }}"

source:
  - url: https://github.com/unicode-org/icu/releases/download/release-{{ version }}/icu4c-{{ version }}-sources.tgz
    sha256: 3a2e7a47604ba702f345878308e6fefeca612ee895cf4a5f222e7955fabfe0c0
    patches:
      # Include an extra header when using mingw.
      - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch  # [win]
      # Omit lib prefix on libraries.
      - icu-config.patch  # [win]
      - mach-port-t.patch  # [osx]

  - url: https://github.com/unicode-org/icu/releases/download/release-{{ version }}/icu4c-{{ version }}-data.zip
    sha256: 9d8b3899096aeb83e4e21ef8a40fec9e03b28db18c48452efac882ce25a91e27
    folder: source/data

build:
  number: 0
  run_exports:
    # icu changes their file extension with each major rev.  Default pin OK.
    - {{ pin_subpackage('icu') }}

requirements:
  build:
    - python 3.11   # [win]
    - m2-base       # [win]
    - m2-make       # [win]
    - m2-sed        # [win]
    - m2-coreutils  # [win]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make     # [unix]
  host:
  run:

test:
  files:
    # From http://source.icu-project.org/repos/icu/data/trunk/charset/data/ucm/gb-18030-2000.ucm
    - gb-18030-2000.ucm
    # From ICU's data folder.
    - de.txt
  commands:
    # Libraries
    {% set libs = [
       "libicudata",
       "libicui18n",
       "libicuio",
       "libicutest",
       "libicutu",
       "libicuuc"
     ] %}
    {% for each_lib in libs %}
    # https://github.com/conda-forge/icu-feedstock/issues/40
    - test ! -f $PREFIX/lib/{{ each_lib }}.a  # [not win]
    - test -f $PREFIX/lib/{{ each_lib }}.{{ version }}.dylib   # [osx]
    - test -f $PREFIX/lib/{{ each_lib }}.so.{{ version }}  # [linux]
    {% endfor %}

    # CLI tests
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help  # [not win]
    - makeconv gb-18030-2000.ucm

about:
  home: https://icu.unicode.org
  license: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
