{% set version = "75.1" %}
{% set version_under = version.replace(".", "_") %}
{% set version_hyphen = version.replace(".", "-") %}

package:
  name: icu
  version: {{ version }}

source:
  - url: https://github.com/unicode-org/icu/releases/download/release-{{ version_hyphen }}/icu4c-{{ version_under }}-src.tgz
    sha256: cb968df3e4d2e87e8b11c49a5d01c787bd13b9545280fc6642f826527618caef
    patches:
      # Include an extra header when using mingw.
      - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch  # [win]
      # Omit lib prefix on libraries.
      - icu-config.patch  # [win]
      - mach-port-t.patch  # [osx]

  - url: https://github.com/unicode-org/icu/releases/download/release-{{ version_hyphen }}/icu4c-{{ version_under }}-data.zip
    sha256: a5104212dc317a64f9b035723ea706f2f4fd5a0f37b7923fae7aeb9d1d0061b1
    folder: source/data

build:
  number: 0
  skip: true  # [not win]
  run_exports:
    # icu changes their file extension with each major rev.  Default pin OK.
    - {{ pin_subpackage('icu') }}

requirements:
  build:
    - m2-base  # [win]
    - m2-make  # [win]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make     # [unix]
  host:
  run:

test:
  files:
    # From http://source.icu-project.org/repos/icu/data/trunk/charset/data/ucm/gb-18030-2000.ucm
    - gb-18030-2000.ucm
    # From ICU's data folder.
    - de.txt
  commands:
    # Libraries
    {% set libs = [
       "libicudata",
       "libicui18n",
       "libicuio",
       "libicutest",
       "libicutu",
       "libicuuc"
     ] %}
    {% for each_lib in libs %}
    # https://github.com/conda-forge/icu-feedstock/issues/40
    - test ! -f $PREFIX/lib/{{ each_lib }}.a  # [not win]
    - test -f $PREFIX/lib/{{ each_lib }}.{{ version }}.dylib   # [osx]
    - test -f $PREFIX/lib/{{ each_lib }}.so.{{ version }}  # [linux]
    {% endfor %}

    # CLI tests
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help  # [not win]
    - makeconv gb-18030-2000.ucm

about:
  home: https://icu.unicode.org
  license: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
